DELETE FROM `weenie` WHERE `class_Id` = 801777;

INSERT INTO `weenie` (`class_Id`, `class_Name`, `type`, `last_Modified`)
VALUES (801777, 'Boosted Cloak of Krampus', 2, '2022-12-01 11:24:57') /* Clothing */;

INSERT INTO `weenie_properties_int` (`object_Id`, `type`, `value`)
VALUES (801777,   1,          4) /* ItemType - Clothing */
     , (801777,   4,     131072) /* ClothingPriority - 131072 */
     , (801777,   5,         75) /* EncumbranceVal */
     , (801777,   9,  134217728) /* ValidLocations - Cloak */
     , (801777,  16,          1) /* ItemUseable - No */
     , (801777,  18,         32) /* UiEffects - Magical */
     , (801777,  19,       5336) /* Value */
     , (801777,  28,          0) /* ArmorLevel */
     , (801777,  36,       9999) /* ResistMagic */
     , (801777,  65,        101) /* Placement - Resting */
     , (801777,  93,       1044) /* PhysicsState - Ethereal, IgnoreCollisions, Gravity */
     , (801777, 105,          8) /* ItemWorkmanship */
     , (801777, 131,          6) /* MaterialType - Silk */
     , (801777, 158,          7) /* WieldRequirements - Level */
     , (801777, 159,          1) /* WieldSkillType - Axe */
     , (801777, 160,        400) /* WieldDifficulty */
     , (801777, 265,         71) /* EquipmentSetId - Ninja */
     , (801777, 352,          1) /* CloakWeaveProc */
	 , (801777, 370,         20) /* Damage */
	 , (801777, 371,         20) /* Damage Resist */
	 , (801777, 374,         20) /* Critical Damage */
	 , (801777, 375,         20) /* Critical Damage Resist */;

INSERT INTO `weenie_properties_bool` (`object_Id`, `type`, `value`)
VALUES (801777,   1, False) /* Stuck */
     , (801777,  11, True ) /* IgnoreCollisions */
     , (801777,  13, True ) /* Ethereal */
     , (801777,  14, True ) /* GravityStatus */
     , (801777,  19, True ) /* Attackable */
     , (801777,  22, True ) /* Inscribable */
     , (801777, 100, False) /* Dyable */
     , (801777, 112, False) /* ProcSpell - Incantation of Heal Self */;

INSERT INTO `weenie_properties_float` (`object_Id`, `type`, `value`)
VALUES (801777,   1,       5) /* HeartbeatInterval */
     , (801777,   2,       0) /* HeartbeatTimestamp */
     , (801777,  13,     0.8) /* ArmorModVsSlash */
     , (801777,  14,     0.8) /* ArmorModVsPierce */
     , (801777,  15,       1) /* ArmorModVsBludgeon */
     , (801777,  16,     0.2) /* ArmorModVsCold */
     , (801777,  17,     0.2) /* ArmorModVsFire */
     , (801777,  18,     0.1) /* ArmorModVsAcid */
     , (801777,  19,     0.2) /* ArmorModVsElectric */
     , (801777, 156,     0.5) /* ProcSpellRate */
     , (801777, 165,       1) /* ArmorModVsNether */;

INSERT INTO `weenie_properties_string` (`object_Id`, `type`, `value`)
VALUES (801777,   1, 'Boosted Cloak of Krampus') /* Name */
     , (801777,  16, 'This cloak is living and breathing. It will grant you great power over time, however, it does get tired and will stop granting you power. Periodically you will need to unwield it and give it a break. Once it has had enough rest, you can wield it again.') /* LongDesc */
     , (801777,  33, 'KrampusCloak') /* Quest */;

INSERT INTO `weenie_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (801777,   1, 0x02001B2A) /* Setup */
     , (801777,   3, 0x20000014) /* SoundTable */
     , (801777,   7, 0x100007E9) /* ClothingBase */
     , (801777,   8,      27569) /* Icon */
     , (801777,  22, 0x3400002B) /* PhysicsEffectTable */
     , (801777,  52,  100676441) /* IconUnderlay */
     , (801777,  55,       4643) /* ProcSpell - Incantation of Drain Health Other */;

INSERT INTO `weenie_properties_emote` (`object_Id`, `category`, `probability`, `weenie_Class_Id`, `style`, `substyle`, `quest`, `vendor_Type`, `min_Health`, `max_Health`)
VALUES (801777, 25 /* Wield */, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

SET @parent_id = LAST_INSERT_ID();

INSERT INTO `weenie_properties_emote_action` (`emote_Id`, `order`, `type`, `delay`, `extent`, `motion`, `message`, `test_String`, `min`, `max`, `min_64`, `max_64`, `min_Dbl`, `max_Dbl`, `stat`, `display`, `amount`, `amount_64`, `hero_X_P_64`, `percent`, `spell_Id`, `wealth_Rating`, `treasure_Class`, `treasure_Type`, `p_Script`, `sound`, `destination_Type`, `weenie_Class_Id`, `stack_Size`, `palette`, `shade`, `try_To_Bond`, `obj_Cell_Id`, `origin_X`, `origin_Y`, `origin_Z`, `angles_W`, `angles_X`, `angles_Y`, `angles_Z`)
VALUES (@parent_id, 0, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 307 /* DamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 1, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 2, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 308 /* DamageResistRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 3, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 4, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 313 /* CritRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 5, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critial Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 6, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 314 /* CritDamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 7, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critical Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 8, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 341 /* LumAugVitality */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 9, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Vitality Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 10, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 307 /* DamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 11, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 12, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 308 /* DamageResistRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 13, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 14, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 313 /* CritRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 15, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critial Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 16, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 314 /* CritDamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 17, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critical Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 18, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 341 /* LumAugVitality */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 19, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Vitality Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 20, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 307 /* DamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 21, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 22, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 308 /* DamageResistRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 23, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 24, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 313 /* CritRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 25, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critial Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 26, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 314 /* CritDamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 27, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critical Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 28, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 341 /* LumAugVitality */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 29, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Vitality Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 30, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 307 /* DamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 31, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 32, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 308 /* DamageResistRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 33, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 34, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 313 /* CritRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 35, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critial Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 36, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 314 /* CritDamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 37, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critical Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 38, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 341 /* LumAugVitality */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 39, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Vitality Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 40, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 307 /* DamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 41, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 42, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 308 /* DamageResistRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 43, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 44, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 313 /* CritRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 45, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critial Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 46, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 314 /* CritDamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 47, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critical Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 48, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 341 /* LumAugVitality */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 49, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Vitality Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 50, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 307 /* DamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 51, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 52, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 308 /* DamageResistRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 53, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 54, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 313 /* CritRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 55, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critial Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 56, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 314 /* CritDamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 57, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critical Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 58, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 341 /* LumAugVitality */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 59, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Vitality Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 60, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 307 /* DamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 61, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 62, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 308 /* DamageResistRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 63, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 64, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 313 /* CritRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 65, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critial Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 66, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 314 /* CritDamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 67, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critical Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 68, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 341 /* LumAugVitality */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 69, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Vitality Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 70, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 307 /* DamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 71, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 72, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 308 /* DamageResistRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 73, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 74, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 313 /* CritRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 75, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critial Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 76, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 314 /* CritDamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 77, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critical Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 78, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 341 /* LumAugVitality */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 79, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Vitality Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 80, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 307 /* DamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 81, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 82, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 308 /* DamageResistRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 83, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 84, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 313 /* CritRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 85, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critial Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 86, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 314 /* CritDamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 87, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critical Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 88, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 341 /* LumAugVitality */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 89, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Vitality Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 90, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 307 /* DamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 91, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 92, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 308 /* DamageResistRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 93, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 94, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 313 /* CritRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 95, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critial Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 96, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 314 /* CritDamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 97, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critical Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 98, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 341 /* LumAugVitality */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 99, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Vitality Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 100, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 307 /* DamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 101, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 102, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 308 /* DamageResistRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 103, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 104, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 313 /* CritRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 105, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critial Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 106, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 314 /* CritDamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 107, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critical Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 108, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 341 /* LumAugVitality */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 109, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Vitality Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 110, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 307 /* DamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 111, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 112, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 308 /* DamageResistRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 113, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 114, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 313 /* CritRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 115, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critial Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 116, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 314 /* CritDamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 117, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critical Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 118, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 341 /* LumAugVitality */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 119, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Vitality Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 120, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 307 /* DamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 121, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 122, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 308 /* DamageResistRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 123, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 124, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 313 /* CritRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 125, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critial Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 126, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 314 /* CritDamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 127, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critical Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 128, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 341 /* LumAugVitality */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 129, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Vitality Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 130, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 307 /* DamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 131, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 132, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 308 /* DamageResistRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 133, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 134, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 313 /* CritRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 135, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critial Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 136, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 314 /* CritDamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 137, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critical Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 138, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 341 /* LumAugVitality */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 139, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Vitality Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 140, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 307 /* DamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 141, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 142, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 308 /* DamageResistRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 143, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 144, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 313 /* CritRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 145, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critial Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 146, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 314 /* CritDamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 147, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critical Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 148, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 341 /* LumAugVitality */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 149, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Vitality Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 150, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 307 /* DamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 151, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 152, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 308 /* DamageResistRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 153, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Damage Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 154, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 313 /* CritRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 155, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critial Damage Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 156, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 314 /* CritDamageRating */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 157, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Critical Resistence Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 158, 54 /* IncrementIntStat */, 14400, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 341 /* LumAugVitality */, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
     , (@parent_id, 159, 18 /* DirectBroadcast */, 0, 1, NULL, 'The Cloak of Krampus has granted you +1 Vitality Rating!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

