-- Kaelith (810001) - Academy weapons

INSERT INTO weenie (class_Id, class_Name, type, last_Modified) VALUES (810001, 'kaelith_academy_vendor', 12, NOW()) ON DUPLICATE KEY UPDATE class_Name = VALUES(class_Name), type = VALUES(type), last_Modified = NOW();

INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (810001, 1, 16) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (810001, 2, 31) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (810001, 6, -1) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (810001, 7, -1) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (810001, 16, 32) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (810001, 25, 250) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (810001, 27, 0) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (810001, 74, 0) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (810001, 75, 0) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (810001, 76, 100000) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (810001, 93, 2098200) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (810001, 113, 1) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (810001, 126, 125) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (810001, 127, 125) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (810001, 133, 4) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (810001, 134, 16) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (810001, 1, True) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (810001, 19, False) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (810001, 39, True) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 1, 5) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 3, 0.16) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 4, 5) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 5, 1) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 11, 300) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 13, 0.9) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 14, 1) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 15, 1.1) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 16, 0.4) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 17, 0.4) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 18, 1) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 19, 0.6) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 37, 1) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 38, 1) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 54, 3) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 64, 1) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 65, 1) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 66, 1) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 67, 1) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 68, 1) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 69, 1) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 70, 1) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 104, 10) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (810001, 125, 1) ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT IGNORE INTO weenie_properties_string (object_Id, type, value) VALUES (810001, 1, 'Kaelith');
INSERT IGNORE INTO weenie_properties_string (object_Id, type, value) VALUES (810001, 5, 'Provisions');
INSERT IGNORE INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (810001, 1, 33554433);
INSERT IGNORE INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (810001, 2, 150994945);
INSERT IGNORE INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (810001, 3, 536870913);
INSERT IGNORE INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (810001, 6, 67108990);
INSERT IGNORE INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (810001, 8, 100667446);
INSERT IGNORE INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) VALUES (810001, 1, 220, 0, 0);
INSERT IGNORE INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) VALUES (810001, 2, 270, 0, 0);
INSERT IGNORE INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) VALUES (810001, 3, 200, 0, 0);
INSERT IGNORE INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) VALUES (810001, 4, 200, 0, 0);
INSERT IGNORE INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) VALUES (810001, 5, 290, 0, 0);
INSERT IGNORE INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) VALUES (810001, 6, 290, 0, 0);
INSERT IGNORE INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) VALUES (810001, 1, 196, 0, 0, 331);
INSERT IGNORE INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) VALUES (810001, 3, 196, 0, 0, 466);
INSERT IGNORE INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) VALUES (810001, 5, 196, 0, 0, 486);
INSERT IGNORE INTO weenie_properties_emote (id, object_Id, category, probability, vendor_Type) VALUES (93150, 810001, 2, 1, 1);
INSERT IGNORE INTO weenie_properties_emote (id, object_Id, category, probability, vendor_Type) VALUES (93151, 810001, 2, 1, 2);
INSERT IGNORE INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, motion, message) VALUES (93150, 0, 10, 0, 1, NULL, 'Welcome, traveler. I stock the Academy''s training weapons -- good for learning the basics of any combat art.');
INSERT IGNORE INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, motion, message) VALUES (93151, 0, 10, 0, 1, NULL, 'May your path be guarded.');
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 12750, 1, 0, 5000, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 12751, 1, 0, 5200, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 12752, 1, 0, 5400, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 12753, 1, 0, 5600, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 12754, 1, 0, 5800, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 12755, 1, 0, 6000, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 12756, 1, 0, 6200, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 12757, 1, 0, 6400, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 12758, 1, 0, 6600, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 12759, 1, 0, 6800, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 12760, 1, 0, 7000, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 41514, 1, 0, 7200, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 45531, 1, 0, 7400, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 45532, 1, 0, 7600, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 45535, 1, 0, 7800, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 45536, 1, 0, 8000, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 45539, 1, 0, 8200, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 45540, 1, 0, 8400, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 45543, 1, 0, 8600, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 45544, 1, 0, 8800, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 45547, 1, 0, 9000, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 45548, 1, 0, 9200, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 45551, 1, 0, 9400, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 45552, 1, 0, 9600, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 45555, 1, 0, 9800, False);
INSERT IGNORE INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (810001, 4, 45556, 1, 0, 10000, False);
