-- DEPRECATED 2026-05-07: Bloodletter + per-tier 179/18 live in DrudgeCharm_BloodletterPerTierRestore_2026-05-07.sql and DrudgeCharm_TierWeenies_World.sql.
-- Do not apply this stub; historical intermediate patches are obsolete.
-- Canonical full reset: DrudgeCharm_TierWeenies_World.sql
-- Forward idempotent: DrudgeCharm_BloodletterPerTierRestore_2026-05-07.sql
